INSERT INTO AGS  (ID, NAME, GROESSE) VALUES (1, 'TENNIS',1);
INSERT INTO AGS  (ID, NAME, GROESSE) VALUES (2, 'COMPUTER',2);
INSERT INTO AGS  (ID, NAME, GROESSE) VALUES (3, 'FUSSBALL',0);
INSERT INTO AGS  (ID, NAME, GROESSE) VALUES (4, 'CHILLEN',2);